# Generated by Django 5.0.2 on 2024-03-10 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_comments_remove_blog_likes_comment_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='createdat',
            new_name='created_at',
        ),
    ]
