# Generated by Django 5.0.2 on 2024-03-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_team_image'),
        ('home', '0002_testimonial_alter_partner_image'),
    ]

    operations = [
    ]
